### ISSUE TITLE
More user friendly handling of the read_output.py path input

### ISSUE THREAD

**Issue by Mateasek** [euratom-software/msesim#5]
The path input
https://github.com/euratom-software/msesim/blob/1102fd63b70aa07b622e0eed7126d3ba3c84cd2f/read_output.py#L17

could be treated in a more user friendly way, for example with:

from os.path import expanduser
path_sim = expanduser("~/PycharmProjects/msesim/runs/benchmarkMAST/output/data/MAST_28101_t200ms_filtered.dat")
#Directory of msesim output
idl.execute("restore, '{0}' , /VERBOSE".format(path_sim))

**Comment by sgibson-mse** [comment]
Finally got round to doing this, added in the 'how to use' comments in tools/load_msesim_output.py :-)
